#!/usr/bin/env bash
###Conjunto de especificaciones que deben respetar los fabricantes de hardware de red
El modelo OSI es un modelo conceptual que caracteriza las funciones de comunicación de un sistema de telecomunicaciones sin tener en cuenta su estructura interna y tecnología subyacentes
El modelo OSI es un modelo que caracteriza las funciones de comunicación de un sistema de telecomunicaciones teniendo muy en cuenta su estructura interna y su tecnología subyacentes ####
2
2
